### Create New Account

POST http://localhost:8080/booking/createNewBookings HTTP/1.1 
content-type: application/json

{
"bookingId" : 6, "bookingVname" : "van", "bookingFrom" : "patan", "bookingDestination" : "rar","date": "2020-01-01"
}


### Get All user 
GET http://localhost:8080/booking/list

### Delete user By Id 
DELETE http://localhost:8080/booking/delete/24