

### Create New Account

POST http://localhost:8080/user/ HTTP/1.1 
content-type: application/json

{
"id" : 4645, 
"uname" : "ram", 
"email" : "email@gmail.com", 
"password" : "emaail@123",
"role":"user"
}


### Get All user 
GET http://localhost:8080/user/


### Get detail by user id
GET http://localhost:8080/user/userdetails/1



### Delete user By Id 
DELETE http://localhost:8080/user/21


### login 
POST http://localhost:8080/user/login HTTP/1.1 
content-type: application/json

{
"email" : "akshay@gmail.com", "password" : "Pass@123"
}



### Book by user id and event id 
POST http://localhost:8080/user/88/userbookings/18 HTTP/1.1 
Content-Type: application/json

{
    "userId" : 3,"bookingVname" : "truck", "bookingFrom" : "pune", "bookingDestination" : "kolkatta","date": "2023-05-06", "typeVahi":"ac", "ttimeTAke": 90 ,"price" : 70000 ,"time":"23:12:00"
}


### list all user current booking

GET http://localhost:8080/user/getcurrentbookings/50

### list all user bookings history

GET http://localhost:8080/user/getbookinghistory/14


### Get all userBooking

GET http://localhost:8080/user/alluserbookings


### cancel Booking slot

DELETE http://localhost:8080/user/8/booking/4


### Create New user feedback

POST http://localhost:8080/user/1/feedback HTTP/1.1 
content-type: application/json

{

"comment": "helloo itis nme","rating": 10.0
}


### Get All feedbacks

GET http://localhost:8080/user/feedback

    