

### Create New Account

POST http://localhost:8080/user/ HTTP/1.1 
content-type: application/json

{
"id" : 465, "uname" : "akshay", "email" : "dgdhdfg@gmail", "password" : "Pass@123"
}


### Get All user 
GET http://localhost:8080/user/

### Delete user By Id 
DELETE http://localhost:8080/user/1


### login 
POST http://localhost:8080/user/login HTTP/1.1 
content-type: application/json

{
"email" : "zwr", "password" : "abcd"
}